"""session-history: index Claude Code session transcripts into a FTS5 SQLite DB."""

from .core import (
    SCHEMA_VERSION,
    FTS5_MISSING_MESSAGE,
    FTS5Unavailable,
    connect,
    fts5_available,
    init_db,
    ingest,
    search,
    show,
    recent,
    actions,
    harvest,
    harvest_commit,
    select_harvest_candidates,
    compressed_view,
    filter_batch_echoes,
    default_db_path,
    default_projects_dir,
    default_inbox_dir,
    load_config,
)

__all__ = [
    "SCHEMA_VERSION",
    "FTS5_MISSING_MESSAGE",
    "FTS5Unavailable",
    "connect",
    "fts5_available",
    "init_db",
    "ingest",
    "search",
    "show",
    "recent",
    "actions",
    "harvest",
    "harvest_commit",
    "select_harvest_candidates",
    "compressed_view",
    "filter_batch_echoes",
    "default_db_path",
    "default_projects_dir",
    "default_inbox_dir",
    "load_config",
]
