"""session-history: index Claude Code session transcripts into a FTS5 SQLite DB."""

from .core import (
    SCHEMA_VERSION,
    FTS5_MISSING_MESSAGE,
    FTS5Unavailable,
    INDEX_MISSING_MESSAGE,
    IndexNotBuilt,
    connect,
    fts5_available,
    index_built,
    init_db,
    ingest,
    search,
    show,
    recent,
    actions,
    default_db_path,
    default_projects_dir,
    load_config,
)

__all__ = [
    "SCHEMA_VERSION",
    "FTS5_MISSING_MESSAGE",
    "FTS5Unavailable",
    "INDEX_MISSING_MESSAGE",
    "IndexNotBuilt",
    "connect",
    "fts5_available",
    "index_built",
    "init_db",
    "ingest",
    "search",
    "show",
    "recent",
    "actions",
    "default_db_path",
    "default_projects_dir",
    "load_config",
]
